# Generated by Django 3.2.3 on 2021-05-14 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 6, 30, 42, 579798, tzinfo=utc)),
        ),
    ]
